### ISSUE TITLE
build on alpine

### ISSUE THREAD

**Issue by mgoltzsche** [visualfc/liteide#1123]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
LiteIDE x37.1

### What version of Go are you using (`go version`)?
go 1.14

### What operating system and processor architecture are you using(`go env`)?
alpine3.11 (musl libc) amd64 container on ubuntu 18.04 host

### What did you do?
After the build was working with x36.3 in my alpine-based container image I wanted to update to x37/x37.1.

The error can be reproduced using this [Dockerfile](https://github.com/mgoltzsche/liteide-docker/blob/8de35c3129be85079064469d14830960ad3aa889/Dockerfile#L7).

### What did you expect to see?
A working build on alpine

### What did you see instead?
The build failed at `QTDIR=/usr/lib/qt5 ./build_linux.sh` because `gettimeofday` and `_PATH_UTMPX` are not available:
```
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp: In member function 'virtual void ShellProcess::setupChildProcess()':
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp:412:5: error: 'gettimeofday' was not declared in this scope
  412 |     gettimeofday(&tv, 0);
      |     ^~~~~~~~~~~~
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp:419:15: error: '_PATH_UTMPX' was not declared in this scope; did you mean 'PATH_MAX'?
  419 |     utmpxname(_PATH_UTMPX);
      |               ^~~~~~~~~~~
      |               PATH_MAX
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp: In function 'char* pty_getproc(int, char*)':
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp:464:27: warning: unused parameter 'tty' [-Wunused-parameter]
  464 | pty_getproc(int fd, char *tty) {
      |                     ~~~~~~^~~
make[3]: *** [Makefile:401: .obj/release-shared/unixptyprocess.o] Error 1
make[3]: Leaving directory '/go/liteide/build/src/3rdparty/ptyqt'
```

I created an [issue in the ptyqt repository](https://github.com/kafeg/ptyqt/issues/3) as well.

**Comment by mgoltzsche** [comment]
This is fixed https://github.com/kafeg/ptyqt/commit/be67327f2a67b28e62795d79eba8c241b02d297e

**Comment by mgoltzsche** [comment]
This happens again today with the latest ptyqt apparently, making my LiteIDE build unreproducible.

**Comment by visualfc** [comment]
> This happens again today with the latest ptyqt apparently, making my LiteIDE build unreproducible.

**Comment by mgoltzsche** [comment]
Actually, old builds are still reproducible but the ptyqt version within this repo does not include the fix anymore somehow.

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/releases/tag/x38.2.1

**Comment by mgoltzsche** [comment]
I can confirm: x38.2.1 fixed the issue.
