### ISSUE TITLE
Failed build with Qt 5.9.5

### ISSUE THREAD

**Issue by iEvgeny** [visualfc/liteide#1074]
Hi!
With one of the last commits i have a build error:
`../../../../liteidex/src/plugins/imageeditor/imageeditorfactory.cpp:16:47: error: ‘imageFormatsForMimeType’ is not a member of ‘QImageReader’`

> Function imageFormatsForMimeType() was introduced in Qt 5.12.

Please fix it. Thanks!
