### ISSUE TITLE
incomplete type ‘QApplication’ used in nested name specifier

### ISSUE THREAD

**Issue by pierrre** [visualfc/liteide#389]
I'm compiling the latest version (master):
```
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DLITEAPP_LIBRARY -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_NO_CAST_TO_ASCII -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DLITEEDITOR_LIBRARY -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I../../../../liteidex/src/plugins/liteeditor -I../../../../liteidex/src/api -I../../../../liteidex/src/utils -I../../../../liteidex/src/3rdparty -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtCore -I.moc/release-shared -I.uic -I. -o .obj/release-shared/liteeditorwidgetbase.o ../../../../liteidex/src/plugins/liteeditor/liteeditorwidgetbase.cpp
../../../../liteidex/src/plugins/liteeditor/liteeditorwidgetbase.cpp: In member function ‘virtual bool LiteEditorWidgetBase::viewportEvent(QEvent*)’:
../../../../liteidex/src/plugins/liteeditor/liteeditorwidgetbase.cpp:2799:13: error: incomplete type ‘QApplication’ used in nested name specifier
         if (QApplication::keyboardModifiers() & Qt::ControlModifier) {
             ^
```

**Comment by pierrre** [comment]
The first bad commit is https://github.com/visualfc/liteide/commit/8d99ef4504f7615cc10efd9c02430e833cde235a

**Comment by visualfc** [comment]
fix it

**Comment by pierrre** [comment]
Thank you! :)
